version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:23.5.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
