version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:23.5.0
    steps:
      - checkout

      # Install Java 17
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> $BASH_ENV
            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      # Android SDK Setup
      - run:
          name: Download Android SDK
          command: |
            cd ..
            mkdir -p android-sdk
            cd android-sdk
            wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
            unzip sdk-tools-linux-4333796.zip

      - run:
          name: Set Environment Variables for Android SDK
          command: |
            echo 'export ANDROID_HOME=$HOME/android-sdk' >> $BASH_ENV
            echo 'export PATH=$PATH:$ANDROID_HOME/tools/bin' >> $BASH_ENV
            echo 'export PATH=$PATH:$ANDROID_HOME/platform-tools' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Accept SDK Licenses
          command: |
            yes | sdkmanager --licenses || exit 0
            yes | sdkmanager --update || exit 0

      # Build or Test Android Project
      - run:
          name: Build Android Project
          command: bundle exec fastlane betaAndroid
